### ISSUE TITLE
Init callback option

### ISSUE THREAD

**Issue by tomaszmichalak** [wttech/gradle-environment-plugin#13]
I want to execute some script inside the container (something like service CLI). It is the common pattern for sample data, installing some additional extensions etc. I understand that resolve executes before the container starts.

Right now, we have:

> resolve, up, reload, dev

I would imagine something like

> resolve, init, up, reload, dev

Example:

```
"magento" {
  init {
    execShell("Install sampledata", "/usr/sbin/install-sampledata")
  }
}
```

**Comment by pun-ky** [comment]
IMO this is the purpose of `up` hook. And if such action should be done once you could write a lock file under /var/my-action to ensure after running that action. Next time simply check if that lock file exists. If yes, skip executing that init action.

FYI up hook is working in that way. GAP writes /var/gap/lock ;) after running whole `up` hook.
