### ISSUE TITLE
Consume Docker image extracted by GAP

### ISSUE THREAD

**Issue by pun-ky** [wttech/gradle-environment-plugin#24]
*   use `docker load` to load AEM dispatcher Docker image provided by GAP - https://github.com/wttech/gradle-aem-plugin/issues/775#issuecomment-708618197 ; do it once if running it all the time on `envUp` will be slow
*   test if the loaded image could be used in `docker-compoer.yml.peb`
*   note that GEP is generic purpose plugin, not only AEM related, so Docker image loading mechanism need to be AEM agnostic / universal

**Comment by krystian-panek-wttech** [comment]
done
