### ISSUE TITLE
environmentUp & Docker Desktop 4.8.1 (78998) issue

### ISSUE THREAD

**Issue by bartlomiej-jackowiak-wttech** [wttech/gradle-environment-plugin#31]
After updating the docker to the latest version, there was a problem with turning on the dispatcher.

The reason for this error is that the `docker compose -p gat-aem down --remove-orphans` function now returns error code 1, not 0

**Comment by krystian-panek-wttech** [comment]
helps for reporting this, will be fixed soon

**Comment by krystian-panek-wttech** [comment]
cool that you found it :)

**Comment by bartlomiej-jackowiak-wttech** [comment]
The functionality has been fixed in the new version of Docker 4.8.2
Now  `docker compose down` returns 0 as in earlier versions.

[Release Note](https://github.com/docker/compose/releases/tag/v2.5.1)

**Comment by krystian-panek-wttech** [comment]
Heh. Ok good to know 😂

**Comment by krystian-panek-wttech** [comment]
So nothing to be fixed
